package com;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestClassOrder;

class CalculatorTest {
	
	static Calculator c1;
	
	@BeforeAll
	static void generateCalculatorObject()
	{
		c1 = new Calculator();
		System.out.println("----Finished----");
	}
	
	static void removeCalculatorObject()
	{
		c1 = null;
		System.out.println("----Finished----");
	}

	@BeforeEach
	void abc()
	{
		System.out.println("Before Each test case this will run");
	}
	
	@AfterEach
	void xyz()
	{
		System.out.println("After Each test case this will run");
	}
	@Test
	void test() {
		assertTrue(true);
	}
		
	@Test
	void testAdd()
	{
		Calculator c1 = new Calculator();
		assertEquals(30,c1.add(10,20), ()->"Sum is not right");
		assertEquals(50,c1.add(30,20), ()->"Sum is not right");
		assertEquals(-10,c1.add(10,-20), ()->"Sum is not right");
		System.out.println("From add method");
	}
	
	
	@Test
	void testDiv() throws Exception
	{
	    Calculator c1 = new Calculator();
	    assertEquals(2, c1.div(10, 5));
	    assertThrows(ArithmeticException.class, () -> c1.div(10, 0));
	    System.out.println("From div method");
	}


}
